version: '3'
volumes:
  postgres_data: {}
  redis:
services:
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      - REDIS_URL=redis://redis:6379/0
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: 'redis:4.0-alpine'
    command: redis-server
    volumes:
      - redis:/data
  sidekiq:
    depends_on:
      - db
      - redis
    build: .
    command: sidekiq
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app